# Generated by Django 3.0.6 on 2020-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_title', models.CharField(max_length=200)),
                ('sample_content', models.TextField()),
                ('sample_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
