# Generated by Django 3.0.6 on 2020-05-25 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200525_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 12, 34, 5, 489779), verbose_name='date published'),
        ),
    ]
